kakaobase/src/app/globals.css, kakaobase/src/app/layout.tsx, kakaobase/src/app/providers.tsx, kakaobase/tailwind.config.ts
- 시스템 설정에 따른 다크모드 세팅 완료
- 필요에 따라 추후 색상 추가 예정
=> [FEAT] 다크모드 세팅

kakaobase/src/components/common/NavBar.tsx
=> [FIX] NAV BAR 수정

kakaobase/package-lock.json, kakaobase/package.json, kakaobase/src/apis/api.tsx, kakaobase/src/apis/auth.tsx, kakaobase/src/app/login/page.tsx, kakaobase/src/components/common/SubmitButton.tsx, kakaobase/src/components/inputs/UserInput.tsx, kakaobase/src/components/user/LoginForm.tsx, kakaobase/src/hooks/useLoginForm.tsx, kakaobase/src/schemas/loginSchema.tsx, kakaobase/src/stores/userStore.tsx, kakaobase/tailwind.config.ts
Close #18 
- 로그인 상태 관리
- 로그인 ui
- 제출 버튼 컴포넌트
- 입력 컴포넌트
=> [ 📌 FEAT] 로그인 기능 구현

kakaobase/src/apis/sendEmail.tsx, kakaobase/src/apis/signup.tsx, kakaobase/src/apis/verifyCode.tsx, kakaobase/src/app/profile/[id]/page.tsx, kakaobase/src/app/signup/step1/page.tsx, kakaobase/src/app/signup/step2/page.tsx, kakaobase/src/components/common/SubmitButtonSmall.tsx, kakaobase/src/components/inputs/CourseSelector.tsx, kakaobase/src/components/inputs/UserInput.tsx, kakaobase/src/components/user/EmailAuthStep.tsx, kakaobase/src/components/user/EmailStep.tsx, kakaobase/src/components/user/PasswordStep.tsx, kakaobase/src/components/user/SignupStep1Form.tsx, kakaobase/src/components/user/SignupStep2Form.tsx, kakaobase/src/hooks/useAuthTimer.tsx, kakaobase/src/hooks/useEmailAuth.tsx, kakaobase/src/hooks/usePasswordStep.tsx, kakaobase/src/hooks/useSingupForm.tsx, kakaobase/src/schemas/emailAuthSchema.tsx, kakaobase/src/schemas/passwordConfirmSchema.tsx, kakaobase/src/schemas/signupStep2Schema.tsx, kakaobase/src/stores/emailAuthStore.tsx, kakaobase/src/stores/signupStore.tsx
Closes #19 
Closes #20 
- 이메일 인증 구현
- 시간 감소 확인
- 비밀번호-비밀번호 확인 유효성 검사
- 회원 가입 1단계
- 회원 가입 2단계
- 과정 선택 컴포넌트 구현
- 회원 가입 2단계 유효성 검사 끝
- 회원가입, 로그인 api 작성한 상태
- api 연결은 안 된 상태
=> [ 📌 FEAT] 회원가입 & 이메일 인증 구현

kakaobase/src/apis/postList.tsx, kakaobase/src/app/alarm/page.tsx, kakaobase/src/app/chat/page.tsx, kakaobase/src/app/layout.tsx, kakaobase/src/app/page.tsx, kakaobase/src/app/profile/[id]/page.tsx, kakaobase/src/components/common/NavBar.tsx, kakaobase/src/components/post/PostCard.tsx, kakaobase/src/components/user/FollowButtonSmall.tsx, kakaobase/src/hooks/usePostCardHook.tsx, kakaobase/src/stores/postStore.tsx
Closes #12 
- 사용자 부분
- 팔로우/언팔로우 버튼
- 유튜브/이미지/내용 조건부 렌더링 처리 완료
- 라우팅 (프로필, 내용 - 상세 페이지, 댓글 - 상세 페이지) 완료
- 좋아요 등록/취소 버튼
- api 단순 코드 작성 (연결 X)
- hook으로 작성하지 않고 우선 전부 useState로 관리함 -> 추후 리팩토링 필요
- 좋아요 수, 댓글 수 - 숫자 포맷팅 함수 필요
- 시간 포맷팅 함수 필요
=> [FEAT] 게시글 컴포넌트 구현 완료

kakaobase/src/app/post/[id]/page.tsx, kakaobase/src/components/common/MiddleBar.tsx, kakaobase/src/components/common/header/Header.tsx, kakaobase/src/components/inputs/CommentInput.tsx, kakaobase/src/components/post/PostCard.tsx, kakaobase/src/components/post/PostCourseSelector.tsx, kakaobase/src/components/post/PostList.tsx, kakaobase/src/components/post/UserInfo.tsx, kakaobase/src/hooks/post/usePostCardDetail.tsx
related with #14 
- middle bar (댓글 표시 부분)
- commentInputBar (댓글 입력 바)
- 게시글 상세 페이지 ui 자체는 구현 완료
- 댓글 유효성 검사는 됐는데 상태 관리가 아직 제대로 구현되지 않음
- commentList도 임의로 postList로 넣은 상태라 확장성 부분에서 가능한지 더 확인해 봐야 함
- 대댓글 디자인/기능 정의 확실하게 잡고 가야 할 듯
=> [FEAT] 상세 페이지 1차 완료

kakaobase/src/components/inputs/CourseSelector.tsx, kakaobase/src/components/inputs/UserInput.tsx, kakaobase/src/components/post/UserInfo.tsx
[displayName 추가]
- CourseSelector.tsx
- UserInput.tsx
[router 문제 해결]
- UserInfo.tsx
=> [FIX] 배포 이슈 - 지저분한 코드 수정

kakaobase/next.config.mjs, kakaobase/src/components/post/UserInfo.tsx
- next.config.mjs 수정
- UserInfo 라우팅 페이지 수정
=> [FIX] 배포 문제 2차 수정

kakaobase/package-lock.json, kakaobase/package.json, kakaobase/src/apis/login.tsx, kakaobase/src/app/layout.tsx, kakaobase/src/hooks/user/useLoginForm.tsx, kakaobase/src/stores/userStore.tsx
- 로그인 시 기기id를 저장하기 위해 uuid 라이브러리가 필요함
- uuid 라이브러리만으로 모듈을 불러오지 못하는 오류 발생
- uuid 모듈 라이브러리를 별도로 설치
- 실제 api 명세에 맞게 login api 요청, 응답 수정
- 실제 로그인 api에 맞게 상태 관리 및 api 처리 수정 (useLoginForm.tsx)
- userId type을 number로 수정
- 모든 페이지에서 토큰 재발급이 가능하도록 layout.tsx에서 설정
- login api 파일에 refresh api 추가
=> [🔨 FIX] 로그인 수정

kakaobase/next.config.mjs, kakaobase/src/apis/sendEmail.tsx, kakaobase/src/apis/signup.tsx, kakaobase/src/apis/verifyCode.tsx, kakaobase/src/app/post/new/page.tsx
- signup.tsx 회원가입 api
- sendEmail.tsx 이메일 전송 api
- verifyCode.tsx 인증 코드 api
- next.config.mjs
- 게시글 작성 페이지 -> csr
=> [FIX] 배포 문제 해결 및 회원 가입 api 수정

kakaobase/src/hooks/user/useLoginForm.tsx
- useLoginForm 훅 파일에서 주석이었던 거 제거
=> [FIX] 로그인 api 성공

kakaobase/src/app/page.tsx, kakaobase/src/components/common/NavBar.tsx, kakaobase/src/hooks/user/useLikeHook.tsx
- navbar - 채팅 주석 처리
- navbar - 알림 주석 처리
- courseSelector 일단 주석 처리
- mockUser 제거하고 프로필 이미지 임시로 등록하기
- 좋아요 등록/취소 응답 콘솔에 출력하는 코드 삭제
=> [COMMET] mvp 맞춤형

kakaobase/src/components/post/PostList.tsx, kakaobase/src/components/post/UserInfo.tsx, kakaobase/src/lib/formatDate.tsx
- formatDate 수정
- 로그인 안됐을 때 login으로 라우팅
=> [HOTFIX] 배포 문제 해결

kakaobase/src/components/post/PostEditor.tsx
=> [HOTFIX] 닉네임 수정

kakaobase/src/apis/imageS3.tsx, kakaobase/src/components/common/NavBar.tsx
=> [HOTFIX] 이미지 url 수정

kakaobase/src/apis/commentList.tsx, kakaobase/src/apis/postList.tsx, kakaobase/src/components/post/CountsInfo.tsx, kakaobase/src/components/post/PostCard.tsx, kakaobase/src/components/post/UserInfo.tsx, kakaobase/src/hooks/post/usePostCardDetail.tsx, kakaobase/src/hooks/post/usePostCardHook.tsx, kakaobase/src/hooks/post/usePostEditorForm.tsx, kakaobase/src/lib/mapPost.tsx, kakaobase/src/stores/postStore.tsx, kakaobase/src/stores/postType.tsx
- postStore.tsx을 postType.tsx로 분리
- PostState -> PostEntity
- onClick 함수 속성들 삭제
- Post, Comment, Recomment 구분을 위해 interface 상속으로 postEntity 리팩토링
- 댓글 목록 조회, 게시글 목록 조회 api PostEntity에 맞게 수정
- CountsInfo, PostCard, UserInfo 컴포넌트에 PostEntity 반영
- 이후 html 삼항연산자에서 undefined 가능성 오류 문제 발생해서 수정
- usePostCardDetail, usePostCardHook에서 PostState -> PostEntity 자료형 선언 수정
- mapPost에서도 매핑되는 entity가 바뀌어 매핑함수 수정
- 게시글 작성 후 메인 화면으로 이동하도록 라우팅 수정
- 이미지 현재 테스트 중이기 떄문에 console 출력 코드 수정
=> [FIX, REFACTOR] post 관련 수정

kakaobase/src/apis/comment.tsx, kakaobase/src/apis/imageS3.tsx, kakaobase/src/components/common/NavBar.tsx, kakaobase/src/lib/getClientCookie.tsx
- getClientCookie에 getAccessToken 함수 작성
- getClientCookie에서 액세스 토큰 받아오는 부분들은 전부 getAccessToken으로 변경
=> [FEAT] accessToken 받고 적용

kakaobase/src/apis/youtubeSummary.tsx, kakaobase/src/components/post/PostCard.tsx, kakaobase/src/hooks/post/useYoutubeHook.tsx, kakaobase/src/schemas/postSchema.tsx
- 스키마 : 유튜브 형식 에러메시지 수정 - postSchema
- 로딩 중 ux 향상 - PostCard.tsx
- 유튜브 요약 응답 api - youtubeSummary.tsx
- useYoutubeHook - 유튜브 상태 관리 훅 작성
=> [FEAT] 유튜브 요약 완성

kakaobase/src/apis/imageS3.tsx, kakaobase/src/components/post/PostCard.tsx
- 게시글 상세에서 게시글 클릭 시, 댓글 상세에서 댓글 클릭 시 페이지 이동하는 문제가 있었음
- presigned_url 오타 있어서 게시글 업로드 안 되는 문제 있었음
-> 수정 완료
=> [FIX] 버그 수정

kakaobase/src/apis/comment.tsx, kakaobase/src/apis/commentList.tsx, kakaobase/src/apis/imageS3.tsx, kakaobase/src/apis/postList.tsx, kakaobase/src/apis/recomment.tsx, kakaobase/src/apis/youtubeSummary.tsx, kakaobase/src/components/common/NavBar.tsx, kakaobase/src/lib/getClientCookie.tsx
- getAccessToken()은 ssr에서 접근할 수 없는 함수 -> 전부 getClientCookie로 변경
=> [FIX] 배포 빌드 시 액세스 토큰 접근 불가 문제 해결

kakaobase/src/app/layout.tsx, kakaobase/src/components/post/CountsInfo.tsx, kakaobase/src/hooks/auth/useEmailAuth.tsx, kakaobase/src/hooks/user/useLikeHook.tsx, kakaobase/src/hooks/user/useLoginForm.tsx
- 백엔드에서 업데이트하지 않는 문제였음
- 그냥 response라는 변수를 안 써서 그거 지움
- 본문 클릭했을 때는 잘 이동하지만 댓글 아이콘 클릭했을 때 post, comment를 구분하지 않는 문제가 있었음
- 댓글의 라우팅이 다른 게시글로 감
-> post.type에 따라 라우팅 url 분기 처리하여 수정 완료
- useLoginForm.tsx
- timer를 멈추고 이미 가입된 이메일이라는 에러 문구를 출력
- useEmailAuth.tsx
- 누르고 있을 때만 pingpong 튐
=> [FIX] 1차 QA 반영 (0.3.4 업로드용)

kakaobase/src/components/post/PostCard.tsx
=> [COMMENT] 요약 보기 버튼 주석 처리

kakaobase/src/app/page.tsx
=> [CHORE] use client 추가

kakaobase/src/hooks/post/useDeleteHook.tsx
- ssr 시점에 호출하는 부분이 게시글 삭제 시에도 있었음
- async 함수 내부로 이동 (csr)
=> [CHORE] localStorage 문제 해결

kakaobase/next.config.mjs, kakaobase/src/components/post/PostCourseSelector.tsx, kakaobase/src/hooks/post/useCourseSelectHook.tsx, kakaobase/src/hooks/post/useDeleteHook.tsx, kakaobase/src/hooks/post/usePostEditorForm.tsx
- courseSelector에서 직접 localStorage를 호출해서 집어 넣는 것이 문제가 될 수도 있음
- setLoading : false로 finally에서 바꾸기
- 로깅 허용하기
- 게시글 삭제 훅에서 직접 localStorage 호출하던 것 처리
=> [HOTFIX] localStorage 4차 수정

kakaobase/src/components/post/PostCard.tsx, kakaobase/src/components/post/PostList.tsx
- 게시글 상세 페이지 두 줄 이상의 게시글 깨짐 주의
- 스크롤 인식 범위 확장
=> [CHORE] 게시글 깨짐 주의

kakaobase/src/apis/imageS3.tsx
- application/octet-stream -> file.type
=> [HOTFIX] s3 업로드 헤더 수정

kakaobase/src/schemas/postSchema.tsx
startsWith('https://www.youtube.com/'), startsWith('https://youtu.be/')
->
includes('youtube.com/'), includes('youtu.be/')
=> [HOTFIX] 유튜브 링크 유효성 수정

kakaobase/src/components/post/PostCard.tsx
- unoptimized 삭제
- 불필요한 tailwind 스타일 속성 삭제
- #92와 연결된 문제였음
=> [REFACTOR] 이미지 lcp 최적화

kakaobase/src/apis/withdraw.tsx, kakaobase/src/app/profile/[userId]/edit/withdraw/page.tsx, kakaobase/src/components/profile/withdraw/Wrapper.tsx, kakaobase/src/hooks/profile/useWithdrawHook.tsx
- ui 구현 완료
- 로직 구현 완료
- api 등록 시 테스트 필요
=> [FEAT] 회원 탈퇴 구현

kakaobase/src/apis/likeList.tsx, kakaobase/src/app/likes/[postType]/[postId]/page.tsx, kakaobase/src/components/likeFollow/UserItem.tsx, kakaobase/src/components/likeFollow/UserList.tsx, kakaobase/src/components/post/CountsInfo.tsx
- ui 구현 완료
- map 함수는 api 연결 후 도입
- api 틀 짜둠
- react-query 추후 도입 예정
=> [FEAT] 좋아요 등록 유저 목록 조회 페이지 ui

kakaobase/src/apis/follow.tsx, kakaobase/src/app/profile/[userId]/followers/page.tsx, kakaobase/src/app/profile/[userId]/followings/page.tsx, kakaobase/src/components/likeFollow/UserList.tsx, kakaobase/src/components/profile/CountInfo.tsx, kakaobase/src/components/profile/Wrapper.tsx
=> [FEAT] 팔로잉/팔로워 목록

kakaobase/package-lock.json, kakaobase/package.json, kakaobase/src/components/common/Modal.tsx, kakaobase/src/components/common/button/HandleButton.tsx, kakaobase/src/components/post/list/PostList.tsx, kakaobase/src/components/profile/CountInfo.tsx, kakaobase/src/components/profile/QR/CopyUrl.tsx, kakaobase/src/components/profile/QR/ProfileModal.tsx, kakaobase/src/components/profile/QR/QrCode.tsx, kakaobase/src/components/profile/Toggle.tsx, kakaobase/src/components/profile/UserInfo.tsx, kakaobase/src/components/profile/Wrapper.tsx
- 프로필 페이지 본인 여부에 따른 버튼 렌더링 추가
- HandleButton 분리
- 컴포넌트 간 간격 맞추기
- countInfo 크기 키우기
- next-qrcode 라이브러리 설치
- QR 코드 생성
- url 복사 기능
- Wrapper 함수 추가 및 위치 재배치
=> [FEAT/FIX] ui 디테일 수정

kakaobase/src/schemas/githubSchema.tsx, kakaobase/src/schemas/signupStep2Schema.tsx
- 빌드 에러 해결
- zod object 객체 내 object 생성해서 제대로 참조되지 않았음
=> [FIX] 깃허브 스키마 통합

kakaobase/src/apis/api.tsx
=> [FIX] 토스트 로직 제거

kakaobase/src/schemas/emailAuthSchema.tsx, kakaobase/src/schemas/emailSchema.tsx, kakaobase/src/schemas/imageSchema.tsx, kakaobase/src/schemas/loginSchema.tsx, kakaobase/src/schemas/passwordConfirmSchema.tsx, kakaobase/src/schemas/passwordSchema.tsx, kakaobase/src/schemas/postSchema.tsx, kakaobase/src/schemas/profileImageSchema.tsx
- imageSchema, emailSchema, passwordSchema, 생성
- 사용되는 스키마 파일 수정
- 비밀번호 메시지 수정
=> [REFACTOR] 스키마 리팩토링

kakaobase/src/components/social/UserFollowerList.tsx, kakaobase/src/components/social/UserFollowingList.tsx, kakaobase/src/components/social/UserLikeList.tsx, kakaobase/src/hooks/social/useFollowersHook.tsx, kakaobase/src/hooks/social/useFollowingsHook.tsx, kakaobase/src/hooks/social/useLikeListHook.tsx
- scrollHook 연결하기
- data-scroll-area 추가하기
- observerRef 인식 부분 추가하기
- isFetching -> isPending
=> [FIX] 좋아요, 팔로우, 팔로잉 목록 스크롤 해결

kakaobase/src/components/profile/CountInfo.tsx, kakaobase/src/hooks/social/useFollowersHook.tsx, kakaobase/src/hooks/social/useFollowingsHook.tsx, kakaobase/src/hooks/user/useFollowHook.tsx
- id 없을 때 undefined 반환하도록
- 팔로우 버튼 즉시 언팔로우, 또는 반대로 변경하도록
- 숫자 클릭할 때만 목록 볼 수 있도록
=> [HOTFIX] 팔로우 관련 수정

.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml, kakaobase/Dockerfile, kakaobase/appspec.yml, kakaobase/scripts/deploy.sh, kakaobase/scripts/health_check.sh
Close #189
- prod/ dev CI/CD 연결
Dockerfile/ deploy.yml/ appspec.yml/ 폴더 scripts/ 추가
=> [FEAT] CI/CD를 위한 workflow/deploy.ym. & Dockerfile 추가

kakaobase/src/features/feeds/comments/ui/RecommentList.tsx
- PostCard key prop이 없음 -> div 태그 제거
=> [HOTFIX] 빌드 에러 수정

.github/workflows/dev-deploy.yml
=> [HOTFIX] dev-deploy.yml 오류 수정3

.github/workflows/dev-deploy.yml
=>  [HOTFIX] AWS SSM 스크립트 수정

.github/workflows/dev-deploy.yml, kakaobase/package.json
pacakge.json에    "type-check": "tsc --noEmit", 추가
=> [HOTFIX] dev-deploy.yml type check를 위한 package.json 수정

kakaobase/src/features/likes/hooks/useLikeHook.tsx
=> [FIX] 좋아요 개수 서버와 상태 연결

kakaobase/src/features/account/ui/MyPageWrapper.tsx, kakaobase/src/widgets/navbar/NavItemProfile.tsx
- 로그인 안 된 사용자가 마이페이지 접근 시도 시 로그인 페이지로 이동하는 로직 추가
- 로딩 중일 때 navbar가 하단에 고정되도록 하기
=> [FIX] 로그인 안 된 사용자 마이페이지 접근 시 페이지 이동 처리

kakaobase/src/features/account/ui/MyPageWrapper.tsx, kakaobase/src/widgets/navbar/NavItemProfile.tsx
- 로그인 안 된 사용자가 마이페이지 접근 시도 시 로그인 페이지로 이동하는 로직 추가
- 로딩 중일 때 navbar가 하단에 고정되도록 하기
=> [MERGE] dev -> main 오류 해결

kakaobase/src/features/alarm/hooks/useAlarmRouting.tsx, kakaobase/src/features/alarm/hooks/useAlarmSwipe.tsx, kakaobase/src/features/alarm/lib/socket.tsx, kakaobase/src/features/alarm/ui/AlarmAction.tsx, kakaobase/src/features/alarm/ui/AlarmItem.tsx
- 라우팅 훅 추가
- 라우팅 훅 추가하면서 e.stopPropagation() 추가
- dev에서 / 적용 안 되는 문제 해결 (socket.tsx)
- e 데이터 타입 추가
=> [FEAT] 알림 관련 페이지 라우팅

kakaobase/src/app/main/page.tsx, kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
=> [DESIGN] 게시글 작성 버튼 위치 변경

kakaobase/src/features/feeds/posts/ui/PostList.tsx, kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx, kakaobase/src/widgets/buttons/GoNewPost.tsx, kakaobase/src/widgets/buttons/GoUp.tsx
- 1차 수정에도 변경되지 않았음
- 확인이 한 번 더 필요
- 모바일에서도 게시글 작성 버튼이 보이도록 css 수정
=> [FIX] 모바일에서 게시글 작성 버튼 보이게

kakaobase/src/app/main/page.tsx, kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx
=> [FIX] 모바일에서 게시글 작성 버튼 보이게 3차

kakaobase/src/features/feeds/comments/stores/recommentFormStateStore.tsx
=> [FIX] 대댓글 작성 시 대댓글 보이도록 유지

kakaobase/src/app/alarm/page.tsx, kakaobase/src/app/chat/page.tsx, kakaobase/src/app/likes/[postType]/[postId]/page.tsx, kakaobase/src/app/main/page.tsx, kakaobase/src/app/post/[postId]/page.tsx, kakaobase/src/app/profile/[userId]/edit/page.tsx, kakaobase/src/app/profile/[userId]/followers/page.tsx, kakaobase/src/app/profile/[userId]/followings/page.tsx, kakaobase/src/features/account/ui/MyPageWrapper.tsx, kakaobase/src/features/account/ui/edit/EditWrapper.tsx, kakaobase/src/features/account/ui/edit/RoutingButtons.tsx, kakaobase/src/features/account/ui/list/CommentList.tsx, kakaobase/src/features/account/ui/list/LikeList.tsx, kakaobase/src/features/account/ui/list/PostList.tsx, kakaobase/src/features/account/ui/password/PasswordEditWrapper.tsx, kakaobase/src/features/account/ui/withdraw/WithdrawWrapper.tsx, kakaobase/src/features/chat/ui/ChatList.tsx, kakaobase/src/features/chat/ui/MessageInput.tsx, kakaobase/src/features/feeds/comments/ui/CommentInput.tsx, kakaobase/src/features/feeds/posts/ui/PostList.tsx, kakaobase/src/widgets/buttons/FloatingButtonGroup.tsx, kakaobase/src/widgets/navbar/NavBar.tsx, kakaobase/src/widgets/navbar/NavItem.tsx
- 댓글 입력 : sticky -> fixed
- 채팅 전송
- 네비게이션바
- 이에 따른 바닥 마진 mb-16 적용
- 좋아요/팔로우 목록 : mb-24 적용
- 마지막 댓글/게시글입니다 -> mb-8 제거
- 프로필 관련 모달 형식 페이지 mx 적용
=> [DESIGN] 하단 고정 컴포넌트 fixed로 변경

kakaobase/src/app/alarm/page.tsx, kakaobase/src/app/chat/page.tsx, kakaobase/src/app/likes/[postType]/[postId]/page.tsx, kakaobase/src/app/main/page.tsx, kakaobase/src/app/post/[postId]/page.tsx, kakaobase/src/app/profile/[userId]/edit/page.tsx, kakaobase/src/app/profile/[userId]/followers/page.tsx, kakaobase/src/app/profile/[userId]/followings/page.tsx, kakaobase/src/features/account/ui/MyPageWrapper.tsx, kakaobase/src/features/account/ui/password/PasswordEditWrapper.tsx, kakaobase/src/features/account/ui/withdraw/WithdrawWrapper.tsx, kakaobase/src/features/chat/ui/MessageInput.tsx, kakaobase/src/features/feeds/comments/ui/CommentInput.tsx, kakaobase/src/widgets/navbar/NavBar.tsx
- 다시 기존 sticky로 수정
- 하단 마진 요소 제거 (mb-16 / mb-24)
=> [FIX] 하단 고정 요소 포지션 수정

kakaobase/src/app/post/[postId]/page.tsx, kakaobase/src/features/feeds/comments/ui/CommentInput.tsx, kakaobase/src/features/feeds/ui/PostCard.tsx
- div 태그에 아무 스타일이 적용되지 않았던 것을 문제 원인으로 추정
=> [FIX] 모바일에서 CommentInput 안 보이는 문제 해결

kakaobase/src/features/feeds/comments/ui/CommentInput.tsx, kakaobase/src/features/feeds/comments/ui/RecommentStateBar.tsx
=> [FIX] commentInput 재시도

kakaobase/src/app/chat/page.tsx
=> [FIX] 채팅 페이지에 다시 네비게이션 바 넣기

kakaobase/src/features/alarm/hooks/useAlarm.tsx, kakaobase/src/features/alarm/lib/socket.tsx, kakaobase/src/features/chat/api/chatList.tsx, kakaobase/src/features/chat/api/chatQueries.tsx, kakaobase/src/features/chat/hooks/useMessageForm.tsx, kakaobase/src/features/chat/stores/chatStore.tsx, kakaobase/src/features/chat/types/ChatPublishingEvent.tsx, kakaobase/src/features/chat/types/ChatServerEvent.tsx, kakaobase/src/features/chat/types/Chats.tsx, kakaobase/src/features/chat/ui/ChatList.tsx
- 백엔드 구현 전부 완료된 상태 아님
- 코드만 작성함
- 테스트는 ai, 백엔드 완료 후 진행 예정
- socket 연결 완료
- 전송 로직 구현 완료
- 응답 오는 거, 목록 조회 아직 확인 불가
- ai 구현 시작 안 한 상태
=> [FEAT] 채팅 로직 구현

kakaobase/src/app/chat/page.tsx, kakaobase/src/features/chat/api/chatQueries.tsx, kakaobase/src/features/chat/hooks/useMessageForm.tsx, kakaobase/src/features/chat/ui/ChatInput.tsx, kakaobase/src/features/chat/ui/ChatList.tsx, kakaobase/src/shared/ui/Toast.tsx
- isComposing 추가
- streaming은 지금 안 됨
- 스크롤 가장 아래가 디폴트이며 위로 스크롤할 경우에는 유지하도록
- scrollRef, data-scroll-area를 같이 하기 위해 page에서 div 이동
- 메시지 중단할 때 토스트 띄우기
=> [FIX] 채팅 페이지 스크롤 / 엔터 문제 해결

kakaobase/package.json, kakaobase/server.js, kakaobase/src/shared/api/api.tsx
- https 환경 세팅
- window.location.href -> Router.push 로 변경
=> [CHORE] https 환경 세팅 및 window 제거

kakaobase/src/app/chat/page.tsx, kakaobase/src/app/globals.css, kakaobase/tailwind.config.ts
=> [REFACTOR] 폰트 2차 적용

.github/workflows/dev-deploy.yml, .github/workflows/prod-deploy.yml
Close #303 
- dev-deploy.yml PR시에만 실행 변경
- prod-deploy.yml 수정
dev-deploy.yml
prod-deploy.yml
=> [ 💜 FE - FIX] CI PR 시 실행 조건 추가, CI/CD 실행 분리

kakaobase/src/app/error.tsx
- not-found와 동일한 양식
- 에러 페이지는 use client여야 함
- RoutingButton 그래서 안 씀
=> [FEAT] 에러 페이지 구현

kakaobase/src/features/alarm/api/alarmCnt.ts, kakaobase/src/features/alarm/ui/AlarmList.tsx, kakaobase/src/widgets/navbar/NavItem.tsx
- 주석 제거
- 응답 반환값 구체화
- 로딩중 변경 - isPending이 없습니다보다 먼저여야 함
=> [FIX/DESIGN] 알림 개수 확인
