100-hours-a-week/22-tenten-fe

kakaobase/src/app/post/new/page.tsx
kakaobase/src/components/post/PostEditor.tsx
kakaobase/src/data/newDummyPost.tsx
kakaobase/src/hooks/post/usePostCardDetail.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/schemas/postSchema.tsx
kakaobase/src/stores/postStore.tsx

- 게시글 작성 페이지 구현
- 게시글 생성용 테스트 더미 데이터 작성
- 게시글 작성 api
- presigned-url, 이미지 등록 api 공부해야 함
- 게시글 작성 상태관리를 위한 store 수정
- api 연결
- 유효성 검사 더 확실하게

[ 📌 FEAT] 게시글 작성 구현

---

kakaobase/.gitignore
kakaobase/src/apis/api.tsx
kakaobase/src/apis/sendEmail.tsx
kakaobase/src/apis/signup.tsx
kakaobase/src/apis/verifyCode.tsx
kakaobase/src/components/user/EmailAuthStep.tsx
kakaobase/src/components/user/PasswordStep.tsx
kakaobase/src/components/user/SignupStep1Form.tsx
kakaobase/src/components/user/SignupStep2Form.tsx
kakaobase/src/hooks/auth/useEmailAuth.tsx
kakaobase/src/hooks/user/useSignupStep1.tsx
kakaobase/src/hooks/user/useSingupStep2.tsx
kakaobase/src/schemas/passwordConfirmSchema.tsx
kakaobase/src/stores/emailAuthStore.tsx

- api base url .env에 추가
- 인증 코드 인증 api 함수명 변경
- api : signup, sendEmail, verifyCode 에러 처리 수정
- 인증 코드가 일치하지 않을 경우 응답에 따라 예외 처리 수정 완료
- 이메일 전송 / 인증코드 api 2개 연결 완전 성공
- useEmailAuth.tsx에서 store에 저장되는 변수는 지역 변수에서 제거
- 지역 / 전역 변수 중복 있었음
- 이에 맞게 EmailAuthStep도 바뀜
- isVerified가 코드 입력 상태와 충돌하는 문제로 isCodeValid 추가
- signup 훅 파일을 두 개로 분리하면서 파일 이름 변경
- useSignupForm -> useSignupStep2
- SignupStep2 컴포넌트 경로도 수정됨
- 비밀번호 수정 시 비밀번호 확인 부분 에러 메시지가 업데이트 되지 않는 문제를 해결
- 컴포넌트에서도 trigger가 필요하여 PasswordStep에 파라미터로 보내도록 수정
- 회원가입 1단계 컴포넌트에 비즈니스 로직 들어간 부분 분리
- useSignupStep1.tsx 파일 추가
- ui에 보이는 과정명 한국어를 백엔드에 요청 보내기 위해 영어로 변환해야 하는 문제 해결
- class_name 속성이 현재 백엔드에서 className으로 돼있음
- 수정 요청 완료
- 백엔드 릴리즈 업데이트 대기 중
- 백엔드 클라우드 배포해야 함

[FIX] 회원가입 api 및 리팩토링 완료

---

kakaobase/src/apis/commentList.tsx
kakaobase/src/apis/imageS3.tsx
kakaobase/src/apis/post.tsx
kakaobase/src/apis/postList.tsx
kakaobase/src/app/post/[id]/comment/[id]/page.tsx
kakaobase/src/components/post/PostList.tsx
kakaobase/src/hooks/post/usePostCardHook.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/lib/courseMap.tsx
kakaobase/src/lib/getClientCookie.tsx
kakaobase/src/lib/mapPost.tsx
kakaobase/src/lib/postType.tsx

- 게시글 목록 조회 api 요청 성공
- postType lib로 분리
- 응답 타입과 postState 타입이 달라 mapping하는 함수 작성
- postType ui, 요청 형식 다른 거 mapping
- cursor 기반 무한 스크롤 성공
- 백엔드 쿼리 파라미터 limits 아니고 limit이라고 함...
- 임시로 게시글 상세페이지와 동일하게 제작
- 나중에 layout.tsx 만들어서 객체지향적으로 바꿔야 함
- 게시글 상세에서 댓글 클릭시 넘어오는 페이지
- 댓글 목록 조회 api
- accessToken을 헤더에 보내야 해서 getClientCookie.tsx 파일 작성
- 쿠키 원하는 거 불러오는 동적 파일
- 게시글 작성, 게시글 조회 api 파일에서 postType이 다른 데서도 많이 쓰여서 파일 분리하면서 지움
- 명세서에는 스네이크 형식인데 구현은 카멜 아니고 스네이크라고 함...
- 임시로 작성한 상태
- 완성은 아님
- 백엔드 아직 인증 객체 문제 해결 안 됨

[FIX] 게시글 도메인 1차 api

---

kakaobase/src/apis/comment.tsx
kakaobase/src/apis/commentList.tsx
kakaobase/src/apis/imageS3.tsx
kakaobase/src/apis/post.tsx
kakaobase/src/apis/postList.tsx
kakaobase/src/components/inputs/CommentInput.tsx
kakaobase/src/components/post/PostCard.tsx
kakaobase/src/components/post/PostList.tsx
kakaobase/src/components/post/UserInfo.tsx
kakaobase/src/hooks/post/usePostCardHook.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/lib/formatYoutube.tsx

- accessToken 헤더에 추가
- 쿠키에서 postType 꺼내서 쓰기
- 이미지 등록 성공
- 유튜브 등록 성공
- content 등록 성공
- 백엔드에서 오는 유튜브 응답과 프론트가 달라 처리하는 함수 추가 ) formatYoutube.tsx
- 반영된 파일 : PostCard.tsx
- formatYoutube.tsx 구현한 걸 사용하여 백엔드에서 전송하는 youtube_url을 youtube_id로 변환하여 ui 제공
- **comment.tsx**
- 답글 생성 api에서 createdAt 제거
- 헤더에 액세스 토큰 추가
- 예러 처리 방식 수정
- **CommentInput.tsx**
- 지금 ui랑 비즈니스 로직 분리 안 돼있는 거 추후에 반영하기
- 댓글 작성 api와 연결하는 로직 추가
- commentList.tsx
- postType은 쿠키에서 꺼내 쓰도록 수정
- usePostEditorForm.tsx
- 게시글 작성에서 이미지 등록 안 되던 문제 함께 해결
- 응답 데이터에서 data하나 더 하위로 들어갔어야 함
- postType 쿠키에서 꺼내서 사용하는 방식 적절히 수정
- console에 출력하는 거 제거
- 불필요한 주석 제거
- **usePostCardHook.tsx**
- 신고 페이지로 이동하면 안 되기 때문에 신고 버튼 제거
- 팔로우/팔로잉 기능 백엔드 v1에서 하지 않기 때문에 제거
- 해당 부분들 주석 처리함
- **UserInfo.tsx**
- 게시글 목록, 게시글 상세, 댓글 상세 페이지에 따라 post 목록이 없을 경우 다르게 보여아 함
-> 삼항 …

[FIX] 게시글 도메인 api, 주석 처리

---

kakaobase/src/apis/post.tsx
kakaobase/src/components/common/MiddleBar.tsx
kakaobase/src/components/inputs/CommentInput.tsx
kakaobase/src/components/post/DeleteModal.tsx
kakaobase/src/components/post/PostCard.tsx
kakaobase/src/components/post/PostEditor.tsx
kakaobase/src/components/post/PostList.tsx
kakaobase/src/components/post/UserInfo.tsx
kakaobase/src/hooks/post/useDeleteHook.tsx
kakaobase/src/hooks/post/usePostCardDetail.tsx
kakaobase/src/hooks/post/usePostCardHook.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx

- 즉시 업데이트 안 돼서 `window.location.reload()` 우선 임시방편으로 넣어둠
- middlebar에 뒤로가기 삭제
- middlebar 댓글/대댓글 조건 처리
- 삭제 모달 화면 반응형으로 수정
- 게시글/댓글/대댓글이 더이상 없을 때 메시지 수정
- 안 쓰는 코드 삭제
- 복수/단수 안 맞는 거 수정 : usePostCardDetail.tsx
- 게시글 작성에서 이미지 업로드할 때 레이블 할당 코드 리팩토링 (사실 상관 없음)
- usePostCardHook.tsx
- cursor 하나 밀려서 반환받는 문제
- cursor lastId로 세팅하는 걸로 수정
- PostCard.tsx
- navigate 범위 수정
- 요약 보기 버튼 우선 mvp 때 없어서 제거
- header에 액세스 토큰 추가
- api, hook 함수명  겹처서 수정
- UserInfo에서 마이페이지 mvp 때 없어서 라우팅 주석 처리
- hook에 실질적으로 삭제 로직 연결

[ FIX/FEAT ] 게시글 도메인 수정 및 게시글 삭제 api

---

kakaobase/src/apis/comment.tsx
kakaobase/src/apis/like.tsx
kakaobase/src/apis/post.tsx
kakaobase/src/components/post/CountsInfo.tsx
kakaobase/src/components/post/UserInfo.tsx
kakaobase/src/hooks/post/useDeleteHook.tsx
kakaobase/src/hooks/user/useLikeHook.tsx

- 현재 댓글 삭제 구현 불가
- 댓글의 type이 post로 돼있음
- post.tsx ) console 출력 문구 제거
- 게시글 좋아요 등록/취소 성공
- 답글 삭제와 마찬가지로 답글, 대댓글 좋아요 등록 취소가 불가능

[FEAT] api 완성

---

kakaobase/src/apis/comment.tsx
kakaobase/src/apis/recomment.tsx
kakaobase/src/components/inputs/CommentInput.tsx
kakaobase/src/hooks/post/useDeleteHook.tsx
kakaobase/src/hooks/post/usePostCardDetail.tsx
kakaobase/src/hooks/post/usePostCardHook.tsx
kakaobase/src/hooks/user/useLikeHook.tsx
kakaobase/src/lib/mapPost.tsx

- 대댓글 작성 구현 : getComment.tsx
- 댓글 작성 api와 동일함
- CommentInput에서 대댓글 작성과 댓글 작성 조건문으로 분리하여 대댓글 작성 구현
- 비즈니스 로직과 분리가 필요
- useDeleteHook : 대댓글 삭제 주석 제거
- 댓글 응답 형태 매핑하는 객체 수정 : usePostCardDetail
- usePostCard : 대댓글 목록 조회
- useLikeHook : 대댓글 좋아요 등록 / 취소 로직 조건문에 추가
- 댓글 - postEntity 매핑할 때 대댓글 수 매핑 속성 수정
- 근데 아직 백엔드 확인 못 함
- 응답이 우선 recomment_count로 오는 걸로 알고 있음
- 대댓글 api 구현
- 대댓글 목록 조회
- 대댓글 삭제
- 대댓글 생성

[FEAT] 대댓글 구현

---

kakaobase/src/components/post/PostCard.tsx

- 메인 페이지 게시글은 2줄만 보이게
- 상세 페이지 하위 페이지들은 전부 보이게
close #84

[FIX] 게시글 글자 수 분기처리

---

kakaobase/src/apis/editProfile.tsx
kakaobase/src/apis/login.tsx
kakaobase/src/app/profile/[userId]/edit/page.tsx
kakaobase/src/components/common/loading/LoadingSmall.tsx
kakaobase/src/components/profile/edit/ImageInput.tsx
kakaobase/src/components/profile/edit/ReadOnlyUserInfo.tsx
kakaobase/src/components/profile/edit/RoutingButtons.tsx
kakaobase/src/components/profile/edit/TopArea.tsx
kakaobase/src/components/profile/edit/Wrapper.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/hooks/profile/useImageEditHook.tsx
kakaobase/src/hooks/user/useLoginForm.tsx
kakaobase/src/schemas/profileImageSchema.tsx

- 프로필 이미지 컴포넌트
- 읽기 전용 사용자 정보 (이름, 과정명)
- 페이지 이동 버튼 컴포넌트
- 스키마 작성 완료
- 이미지 등록 hook 작성 완료
- TopArea 컴포넌트에 hook 호출 및 props 전달
- ImageInput 컴포넌트에서 이미지 등록 로직 추가
- 토스트 메시지는 추후 구현
- 프로필 이미지 수정 api 작성
- 로그인 프로필 이미지 - localStorage
- 로딩 중 ui 일부 수정
- 게시글 등록 시 액세스 토큰 확인 로직 일부 수정
- 스웨거에 아직 프로필 이미지 등록 api가 올라오지 않음
- 깃허브 url 수정api도 올라오지 않아 #114 - api 관련 이슈 파서 진행 예정

[FEAT] 프로필 편집 구현

---

kakaobase/src/apis/login.tsx
kakaobase/src/app/profile/[userId]/page.tsx
kakaobase/src/components/common/NavBar.tsx
kakaobase/src/components/common/button/SubmitButton.tsx
kakaobase/src/components/profile/CountInfo.tsx
kakaobase/src/components/profile/Toggle.tsx
kakaobase/src/components/profile/UserInfo.tsx
kakaobase/src/components/profile/Wrapper.tsx
kakaobase/src/hooks/user/useLoginForm.tsx

- 마이페이지 ui 구현 완료
- navbar에서 프로필 클릭 시 라우팅 완료
- 프로필 편집 페이지로 라우팅 완료
- 게시글/댓글/좋아요 선택 토글
- member_id 응답 추가
- 커스텀 훅 -> 로컬 스토리지 저장 수정
- 더 크게 xs -> sm

[FEAT] 마이페이지 ui 구현

---

kakaobase/src/apis/postList.tsx
kakaobase/src/app/ToastContext.tsx
kakaobase/src/app/providers.tsx
kakaobase/src/components/common/Toast.tsx
kakaobase/src/components/post/UserInfo.tsx
kakaobase/src/components/profile/QR/CopyUrl.tsx
kakaobase/src/components/profile/edit/ImageInput.tsx
kakaobase/src/hooks/auth/useEmailAuth.tsx
kakaobase/src/hooks/post/comment/useCommentForm.tsx
kakaobase/src/hooks/post/useDeleteHook.tsx
kakaobase/src/hooks/post/usePostDetailHook.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/hooks/profile/useImageEditHook.tsx
kakaobase/src/hooks/profile/useWithdrawHook.tsx
kakaobase/src/hooks/user/useLoginForm.tsx
kakaobase/src/hooks/user/usePasswordStep.tsx
kakaobase/src/hooks/user/useSingupStep2.tsx
kakaobase/src/hooks/user/useTokenCheckHook.tsx

- ui
- 로직
- 프로필 링크 공유 복사 완료 메시지 테스트 완료
- 토스트 Context 생성
-> ToastContext.tsx 작성
-> providers에 적용
-> Toast 컴포넌트에서 useToast 불러오는 방식으로 로직 수정
-> 프로필 공유 링크 복사에도 수정하여 적용
- 게시글/댓글/대댓글 삭제 시 토스트 출력
- 게시글 상세 조회
- 게시글 업로드 시
- 프로필 이미지 저장 시
- 회원 탈퇴 시
- 로그인 시
- 비밀번호 변경 시
- 회원 가입 시
- 토큰 재발급 시
- 기타 오류 시 console -> 토스트 출력

[FEAT] 토스트 추가

---

kakaobase/src/apis/editProfile.tsx
kakaobase/src/apis/login.tsx
kakaobase/src/components/profile/QR/CopyUrl.tsx
kakaobase/src/components/profile/edit/ImageInput.tsx
kakaobase/src/components/profile/edit/TopArea.tsx
kakaobase/src/components/profile/edit/Wrapper.tsx
kakaobase/src/hooks/auth/useEmailAuth.tsx
kakaobase/src/hooks/profile/useGithubEditHook.tsx
kakaobase/src/hooks/profile/useImageEditHook.tsx
kakaobase/src/hooks/profile/useWithdrawHook.tsx
kakaobase/src/hooks/user/useLoginForm.tsx
kakaobase/src/schemas/githubSchema.tsx
kakaobase/src/schemas/signupStep2Schema.tsx

- 이모지 추가
- 깃허브 링크 수정 api
- 프로필 이미지 수정 api 인증 param 위치 수정 (잘못된 곳에 넣고 있었음)
- 깃허브 링크 schema 작성
- 회원 가입 2단계에서도 githubSchema 적용
- 깃허브 수정용 커스텀 훅 작성
- UserInput, 제출 버튼 컴포넌트에 적용
- 가입되지 않은 경우 이메일에 에러 표시
- 로그인 시 프로필 이미지 반환 없음 -> 제거
- 로그인 시 localStorage 삭제 - 전역 상태 관리 사용으로 바꾸기
- 탈퇴 시 로그인 페이지로 이동
- 이름, 닉네임, 과정 - zustand에서 가져오기 (전역으로 관리하도록 변경)
- 프로필 이미지 - zustand로 수정 및 불필요한 출력 메시지 삭제

[FEAT] 프로필 편집/탈퇴 로직 구현

---

kakaobase/src/apis/commentList.tsx
kakaobase/src/components/post/PostCard.tsx
kakaobase/src/lib/mapPost.tsx
kakaobase/src/stores/postType.tsx

- 마이페이지에서 댓글 클릭 시 제대로 된 경로로 라우팅되지 않는 문제 해결
- 댓글 엔티티에 postId 추가 및 post_id 연결

[FIX] 댓글에서 post id 추적

---

kakaobase/src/components/social/UserItem.tsx
kakaobase/src/hooks/social/useFollowersHook.tsx
kakaobase/src/hooks/social/useFollowingsHook.tsx

- 팔로워 목록 조회/ 팔로잉 목록 조회가 반대였음
- UserItem에서도 data.id가 아닌 하드코딩 값으로 라우팅하고 있있음 -> 둘다 해결

[FIX] 팔로잉/팔로워 부분 수정

---

kakaobase/src/apis/login.tsx
kakaobase/src/apis/post.tsx
kakaobase/src/components/common/NavBar.tsx
kakaobase/src/components/post/PostCourseSelector.tsx
kakaobase/src/components/post/PostEditor.tsx
kakaobase/src/components/profile/Wrapper.tsx
kakaobase/src/hooks/post/list/usePostList.tsx
kakaobase/src/hooks/post/useCourseSelectHook.tsx
kakaobase/src/hooks/post/useDeleteHook.tsx
kakaobase/src/hooks/post/usePostDetailHook.tsx
kakaobase/src/hooks/post/usePostEditorForm.tsx
kakaobase/src/hooks/profile/useImageEditHook.tsx
kakaobase/src/hooks/user/useLoginForm.tsx
kakaobase/src/lib/Course.tsx
kakaobase/src/lib/postType.tsx
kakaobase/src/stores/userStore.tsx

- 사용자 개인 정보를 받을 수 있는 방법이 없어 부득이하게 전역상태를 localStorage에 넣고 있음
- 로그인 시, 사용자가 상단 게시글 유형(course) 변경 시 localStorage 안 쓰게 함
- 이외 localStorage 코드 전부 제거
- course 로직 수정
- 게시글 작성, 삭제 시 postType 테스트 완료
- 전역 상태 : profileImageUrl -> imageUrl
- postType 파일명 변경 : postType -> Course

[REFACTOR] localStorage 제거

---

kakaobase/src/app/unauthorized/page.tsx
kakaobase/src/features/feeds/posts/hooks/usePostEditorForm.tsx
kakaobase/src/shared/api/api.tsx

- 인터셉터에서 바로 로그인 페이지가 아닌 인증 안 됨 페이지로 이동하도록 함
- unauthorized 페이지에서 이동할 페이지를 선택하는 모달로 페이지 구현
- 게시글 작성 시 불필요한 catch문의 분기 제거
--- 
- 인터셉터에서 토스트를 띄우는 걸 생각했으나 zustand로 토스트를 이중 구현할 생각이 없음
- 인터셉터에서 훅을 사용할 수 없음 (훅 규칙)
- 사용자에게 선택권을 주는 것이 단순 트스트 이후 페이지 이동하는 것보다 ux가 좋다고 판단

[FIX] 로그인 안 된 사용자를 위한 페이지 구현

---

kakaobase/src/app/providers.tsx
kakaobase/src/features/alarm/hooks/useAlarm.tsx
kakaobase/src/features/alarm/hooks/useAlarmSwipe.tsx
kakaobase/src/features/alarm/lib/socket.tsx
kakaobase/src/features/alarm/types/AlarmResponse.tsx
kakaobase/src/features/alarm/ui/AlarmItem.tsx
kakaobase/src/features/alarm/ui/AlarmList.tsx

- providers.tsx에서 제거
- 알림 응답 데이터 타입 분리
- 메모리 누수 방지를 위해 언마운트될 때 함수 주석 무효화
- 소켓 연결을 보장하기 위해 조건문 추가 (socket.tsx)
- alarmList - 복수에서 단수형으로 변경 (알림 아이템 하나이기 때문)
- 읽지 않은 알림의 경우 파란색 동그라미 추가
- 드래그 시 클릭처럼 페이지 이동하는 현상 발생 -> 드래그 상태를 추가하여 페이지 이동 방지
- 401 에러 (로그인 안 된 사용자일 경우 리프레시 후 소켓 재연결 시도)

[FIX] 알림 안정화 

---

kakaobase/src/shared/api/api.tsx

- 소켓 연결 401 실패 후, 토큰 재발급도 실패할 경우, unauthorized 페이지로 무한 이동하고 이 과정이 반복되는 문제가 있었음 -> Router 사용하여 해결

[FIX] 무한 새로고침 문제 해결

---

kakaobase/package.json
kakaobase/server.js

- 배포 서버에서 npm start로 실행하는데 멋대로 바꿔서 배포 서버에서 실행하는 명령어가 바뀌어 502 gateway를 뱉음
- start:local 명령어 만들게 됨
- server.js도 forceHttps 조건을 추가하여 분기

[FIX] 배포 서버에서 build 명령어 충돌

---

kakaobase/src/features/auth/hooks/useSingupStep2.tsx

- 이베일/비밀번호 입력되지 않는 경우에 대한 예외를 분리하여 toast로 안내
- useEffect 제거

[FIX] 회원가입 로직 수정
